language: node_js
node_js:
- '0.12'
addons:
  sauce_connect: true
env:
  global:
    - secure: mJ5B4uaYZPE0M+IYFVb8pV62KN/5P6KSa3DMueapKXAEdqvqyw85pF6QPGA3vygzx2BiLZCJjPoqEAs0Vt+yewx/EHZt/fF3yIIUfKlLQiTBsVeI26IGp0Rxa4vqqe2K6ws/ToRko/A+jgfrQGI3rm1Ir8et5S5BtUZISp1a24d79Ldzh9GxCZ3KIfWdNO/AphD0+Tg5LUDgxplHnocrq6y7uIFHvCukWPKVVaOniozUEG5ITU1NJVVzgtnygsThfW/dwRxGLLxLwlZ1lSf5vzFbAYv2cixC0tSSxCw2v16ECYaa6AUgNAWOKgLYg7H2iudGHBytwQOF5rSgK2nB5PN/KqgBejxYCnDVgd70p0aJUpKH62NX8pVMTUgK0igKQRA2HlbEKAjzeaREtRyrbgGLbYW+a3iQN4hOzGefwEdEFdXplJCDJn/OZWcIErhiZga9rpNHCpgrRjAHbHdkwAFJ1s5sZpBUm56GZjR40qdIec7m4VxT4sqiQXrMtMD51GRAsl9QmFePb04uRN2gRMJFyePQyQmh5NIwct3DdUh6knqEetCgmwsmHTdBZ6nTxQeSTP9vR3RqI+6I5mSeQCJneCr2MHn5yprZbY53oGr/3gVsypaPI+JTk7i/f9xnJEOFTjSUMRdgxkCN+t2tFeSmUXt6tfZ5DdjypJ+FWDM=
    - secure: B+e5n6yFEd7TqW/qIBCjrdXRXi4+qVCXd9Vv1LX+JPulfFNW66MT/+u1EbXNBYUrH/TapK9NbBFz6NHKS/1zXTnBc/imupN+8q1UJWVWqZUxz4+BSUUrd2i9DJZaxapQg41IB41yH9MaVDZefWVT8rKMP62ZXMFXUfNInQSicmSHe6wRd5sEFuuuI8K0ExB/Zy03Wk/krJvNjVYj3j5nC6qZXO/2K0gutmSqPYZtAnQlohEK0An32qN31gIG4isn9XtY5xzgGU6+79GZ4fthAUu7S7LxfROGBlPSYCYmjD6jWogr+FvcJ8oQESOmrRQTbhSDrOf6tvNb20hA0bsAJcJkkQAf3SSMUuVq7EtGX4pBifryk3a00DmcN8dbx1ErK1Qmdgw60EQ6GTibIrhe5uHb9jCa8I3z0ElxMOCMg3O8PWHn4ysemam+rxoHq+9sc4zpIB69Bg87lAxgbS7lGkRSkExM+GiPLpqEDsBIKg9/Fe0zy7hoi3lvwsAgq4o0byEIokyarHu9duOqT4e4ciGxAE4prxdIBpexuVL/wJkL68oNyNyLcnosoty6PO1HEYFqF1xlw1luD0peDJME9Zdv0DFlBwuHDjsU/jSx5eDSPYxZr3dZJTMAzG1P89Wb0krwdNGbDzhCGrmE/gQzCsVYKNYCNoEzrs6VEgKugT0=

before_script:
  - python -m SimpleHTTPServer &
  - sleep 2